# Site settings
title: "Code Astra: Extreme Web and Mobile App Development."
# email: your-email@domain.com
description: > # Code Astra strives to build innovative products.
  Code Astra is known to deliver value to clients and customers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.codeastra.com" # the base hostname & protocol for your site
twitter_username: CodeAstra
github_username:  CodeAstra
repository: CodeAstra/labs
exclude: [node_modules, gulpfile.js]

# Build settings
markdown: kramdown

# Custom Tags
app_name_tag: '<span class="brand_name">Code Astra</span>'

gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
